<?php

global $alphabet;
$alphabet = array(
    'a' => 0,
    'b' => 1,
    'c' => 2,
    'd' => 3,
    'e' => 4,
    'f' => 5,
    'g' => 6,
    'h' => 7,
    'i' => 8,
    'j' => 9,
    'k' => 10,
    'l' => 11,
    'm' => 12,
    'n' => 13,
    'o' => 14,
    'p' => 15,
    'q' => 16,
    'r' => 17,
    's' => 18,
    't' => 19,
    'u' => 20,
    'v' => 21,
    'w' => 22,
    'x' => 23,
    'y' => 24,
    'z' => 25
);

function shift_cipher_menu() {
    $items = array();
    $items['shift_cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['shift_cipher_success_page'] = array(
        'title' => 'Coded Results',
        'page callback' => 'shift_cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function shift_cipher_form() {
    $form['shift_spaces'] = array(
      '#title' => 'Shift Spaces',
      '#type' => 'textfield',
      '#description' => t('Enter the number of spaces to shift.'),
      '#required' => TRUE,
      '#element_validate' => array('element_validate_integer', 'element_validate_number_range'),
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Enter a direction. (left or right)'),
        '#required' => TRUE,
        '#element_validate' => array('element_validate_left_right'),
    );
    $form['user_input'] = array(
      '#title' => 'Message',
      '#type' => 'textfield',
      '#description' => t('Enter a message to encode.'),
      '#required' => TRUE,
      '#element_validate' => array('element_validate_letters_punctuation'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encode Message!',
    );
    return $form;
}

function element_validate_number_range($element) {
    $number_input = $element['#value'];
    if (($number_input == 0) || ($number_input % 26 == 0)) {
        form_set_error('shift_spaces', 'Cannot encode with a shift value of ' . $number_input . '. The message will be the same!');
    } elseif ($number_input < 0) {
        form_set_error('shift_spaces', 'Shift Spaces must be a positive integer.');
    }
}

function element_validate_left_right($element) {
    $direction = array('left', 'right');
    $direction_input = strtolower($element['#value']);
    if (!(in_array($direction_input, $direction))) {
        form_set_error('shift_direction', 'Incorrect input, please enter left or right');
    }
}

function element_validate_letters_punctuation($element) {
    $user_input = str_split($element['#value']);
    foreach ($user_input as $input) {
        if ((preg_match("/[^a-zA-Z0-9\s\p{P}]/", $input))) {
            form_set_error('user_input', 'Invalid character(s) in the message!');
        }
    }
}

function shift_cipher_form_submit($form, &$form_state) {
    $shift_spaces = $form_state['values']['shift_spaces'];
    $shift_direction = $form_state['values']['shift_direction'];
    $user_input = str_split(strtolower($form_state['values']['user_input']));
    $output = array();
    global $alphabet;
    foreach ($user_input as $input) {
        if (in_array($input, $alphabet)) {
            $input = $alphabet[$input];
            array_push($output, $input);
        }
    }

    $_SESSION['shift_cipher'] = $output;
    $form_state['redirect'] = 'shift_cipher_success_page';
}

function shift_cipher_success() {
    $output = $_SESSION['shift_cipher'];
    var_dump($output);
    return '<p>results: ' . $output . '</p>';
}
