<?php

global $alphabet;
$alphabet = array(
    '0' => 'a',
    '1' => 'b',
    '2' => 'c',
    '3' => 'd',
    '4' => 'e',
    '5' => 'f',
    '6' => 'g',
    '7' => 'h',
    '8' => 'i',
    '9' => 'j',
    '10' => 'k',
    '11' => 'l',
    '12' => 'm',
    '13' => 'n',
    '14' => 'o',
    '15' => 'p',
    '16' => 'q',
    '17' => 'r',
    '18' => 's',
    '19' => 't',
    '20' => 'u',
    '21' => 'v',
    '22' => 'w',
    '23' => 'x',
    '24' => 'y',
    '25' => 'z'
);

function shift_cipher_menu() {
    $items = array();
    $items['shift_cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['shift_cipher_success_page'] = array(
        'title' => 'Coded Results',
        'page callback' => 'shift_cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function shift_cipher_form() {
    $form['shift_spaces'] = array(
      '#title' => 'Shift Spaces',
      '#type' => 'textfield',
      '#description' => t('Enter the number of spaces to shift.'),
      '#required' => TRUE,
      '#element_validate' => array('element_validate_number_range'),
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Enter a direction. (left or right)'),
        '#required' => TRUE,
        '#element_validate' => array('element_validate_left_right'),
    );
    $form['user_input'] = array(
      '#title' => 'Message',
      '#type' => 'textfield',
      '#description' => t('Enter a message to encode.'),
      '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encode Message!',
    );
    return $form;
}

function element_validate_number_range($element) {
    $number_input = $element['#value'];
    if (($number_input == 0) || ($number_input % 26 == 0)) {
        form_set_error('shift_spaces', 'Cannot encode with a shift value of ' . $number_input . '. The message will be the same!');
    } elseif ($number_input < 0) {
        form_set_error('shift_spaces', 'Shift Spaces must be a positive integer.');
    }
}

function element_validate_left_right($element) {
    $direction = array('left', 'right');
    $direction_input = strtolower($element['#value']);
    if (!(in_array($direction_input, $direction))) {
        form_set_error('shift_direction', 'Incorrect input, please enter left or right');
    }
}

function shift_cipher_form_submit($form, &$form_state) {
    $shift_spaces = $form_state['values']['shift_spaces'];
    $shift_direction = $form_state['values']['shift_direction'];
    $user_input = strtolower($form_state['values']['user_input']);
    $output = '';
    $output = $user_input . ' ' . $shift_direction . ' ' . $shift_spaces;

    $_SESSION['shift_cipher'] = $output;
    $form_state['redirect'] = 'shift_cipher_success_page';
}

function shift_cipher_success() {
    $output = $_SESSION['shift_cipher'];
    return '<p>results: ' . $output . '</p>';
}
