<?php

function shift_cipher_menu() {
    $items = array();
    $items['shift_cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['shift_cipher_success_page'] = array(
        'title' => 'Coded Results',
        'page callback' => 'shift_cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function shift_cipher_form() {
    $form['shift_spaces'] = array(
      '#title' => 'Shift Spaces',
      '#type' => 'textfield',
      '#description' => t('Enter the number of spaces to shift.'),
      '#required' => TRUE,
      '#element_validate' => array('element_validate_number'),
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Enter a direction. (right or left)'),
        '#required' => TRUE,
    );
    $form['user_input'] = array(
      '#title' => 'Message',
      '#type' => 'textfield',
      '#description' => t('Enter a message to encode.'),
      '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encode Message!',
    );
    return $form;
}

function shift_cipher_form_submit($form, &$form_state) {
    $shift_spaces = $form_state['values']['shift_spaces'];
    $shift_direction = $form_state['values']['shift_direction'];
    $user_input = strtolower($form_state['values']['user_input']);
    $output = '';
    $output = $user_input . ' ' . $shift_direction . ' ' . $shift_spaces;

    $_SESSION['shift_cipher'] = $output;
    $form_state['redirect'] = 'shift_cipher_success_page';
}

function shift_cipher_success() {
    $output = $_SESSION['shift_cipher'];
    return '<p>results: ' . $output . '</p>';
}
